apiVersion: v1
kind: Namespace
metadata:
  name: app
---
# nginx-service-nlb.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    myapp: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosg-webapp
  namespace: app
  labels:
    myapp: app
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: app
  template:
    metadata:
      labels:
        myapp: app
    spec:
      containers:
      - name: app
        image: 924841524423.dkr.ecr.eu-west-1.amazonaws.com/k8s_sm:v1.0
        env:
          - name: APP_COLOR
            value: "green"
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        ports:
        - containerPort: 8080