apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    deploy: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer