apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
#    istio: ingressgateway
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP